services:
  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    networks:
      - php-native-network
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./app/:/var/www/html/
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - php-native-network
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysqldb
    networks:
      - php-native-network

networks:
  php-native-network:
    external: true